/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  AggregatorMockUSDC,
  AggregatorMockUSDCInterface,
} from "../AggregatorMockUSDC";

const _abi = [
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "latestRoundData",
    outputs: [
      {
        internalType: "uint80",
        name: "",
        type: "uint80",
      },
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint80",
        name: "",
        type: "uint80",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060b38061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c8063313ce567146037578063feaf968c14604b575b600080fd5b604051600881526020015b60405180910390f35b6040805160018082526305f625a6602083015260009282018390526060820192909252608081019190915260a001604256fea264697066735822122028668fd574b52e18d1c37c2c3df90e538a6b0a1d0cf0ea0d5255b847e9da064564736f6c634300080a0033";

export class AggregatorMockUSDC__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<AggregatorMockUSDC> {
    return super.deploy(overrides || {}) as Promise<AggregatorMockUSDC>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): AggregatorMockUSDC {
    return super.attach(address) as AggregatorMockUSDC;
  }
  connect(signer: Signer): AggregatorMockUSDC__factory {
    return super.connect(signer) as AggregatorMockUSDC__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AggregatorMockUSDCInterface {
    return new utils.Interface(_abi) as AggregatorMockUSDCInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AggregatorMockUSDC {
    return new Contract(address, _abi, signerOrProvider) as AggregatorMockUSDC;
  }
}
