/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITHEOERC20, ITHEOERC20Interface } from "../ITHEOERC20";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    name: "burnFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITHEOERC20__factory {
  static readonly abi = _abi;
  static createInterface(): ITHEOERC20Interface {
    return new utils.Interface(_abi) as ITHEOERC20Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITHEOERC20 {
    return new Contract(address, _abi, signerOrProvider) as ITHEOERC20;
  }
}
