/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IYieldReporter,
  IYieldReporterInterface,
} from "../IYieldReporter";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "int256",
        name: "yield",
        type: "int256",
      },
    ],
    name: "ReportYield",
    type: "event",
  },
  {
    inputs: [],
    name: "currentYield",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "getYieldById",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lastYield",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "_amount",
        type: "int256",
      },
    ],
    name: "reportYield",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IYieldReporter__factory {
  static readonly abi = _abi;
  static createInterface(): IYieldReporterInterface {
    return new utils.Interface(_abi) as IYieldReporterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IYieldReporter {
    return new Contract(address, _abi, signerOrProvider) as IYieldReporter;
  }
}
