/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { SignerHelper, SignerHelperInterface } from "../SignerHelper";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_data",
        type: "string",
      },
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "address",
        name: "_contractAddress",
        type: "address",
      },
      {
        internalType: "string",
        name: "_secret",
        type: "string",
      },
    ],
    name: "createHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061030e806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80630be442ea14610030575b600080fd5b61004361003e366004610132565b610055565b60405190815260200160405180910390f35b6000838587858560405160200161007095949392919061024e565b60405160208183030381529060405280519060200120905095945050505050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b803573ffffffffffffffffffffffffffffffffffffffff811681146100e457600080fd5b919050565b60008083601f8401126100fb57600080fd5b50813567ffffffffffffffff81111561011357600080fd5b60208301915083602082850101111561012b57600080fd5b9250929050565b60008060008060006080868803121561014a57600080fd5b853567ffffffffffffffff8082111561016257600080fd5b818801915088601f83011261017657600080fd5b81358181111561018857610188610091565b604051601f82017fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe0908116603f011681019083821181831017156101ce576101ce610091565b816040528281528b60208487010111156101e757600080fd5b8260208601602083013760006020848301015280995050505061020c602089016100c0565b955061021a604089016100c0565b9450606088013591508082111561023057600080fd5b5061023d888289016100e9565b969995985093965092949392505050565b60007fffffffffffffffffffffffffffffffffffffffff000000000000000000000000808860601b168352808760601b16601484015250845160005b818110156102a7576020818801810151602886840101520161028a565b818111156102b9576000602883860101525b508201838560288301376000930160280192835250909594505050505056fea2646970667358221220a44fa4f53c5c6ad6f2bfdb8737ce94f65fe7bf49bdab6377713757552bba19e164736f6c634300080a0033";

export class SignerHelper__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SignerHelper> {
    return super.deploy(overrides || {}) as Promise<SignerHelper>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SignerHelper {
    return super.attach(address) as SignerHelper;
  }
  connect(signer: Signer): SignerHelper__factory {
    return super.connect(signer) as SignerHelper__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SignerHelperInterface {
    return new utils.Interface(_abi) as SignerHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SignerHelper {
    return new Contract(address, _abi, signerOrProvider) as SignerHelper;
  }
}
