/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface StakingDistributorInterface extends ethers.utils.Interface {
  functions: {
    "addRecipient(address,uint256,int256,int256,bool)": FunctionFragment;
    "adjustments(uint256)": FunctionFragment;
    "authority()": FunctionFragment;
    "bounty()": FunctionFragment;
    "deriveRate(uint256)": FunctionFragment;
    "distribute()": FunctionFragment;
    "epochLength()": FunctionFragment;
    "info(uint256)": FunctionFragment;
    "nextRewardAt(uint256,address)": FunctionFragment;
    "nextRewardFor(address)": FunctionFragment;
    "nextRewardRate(uint256)": FunctionFragment;
    "removeRecipient(uint256)": FunctionFragment;
    "retrieveBounty()": FunctionFragment;
    "setAuthority(address)": FunctionFragment;
    "setBounty(uint256)": FunctionFragment;
    "setDiscountRateStaking(uint256,int256)": FunctionFragment;
    "setDiscountRateYield(uint256,int256)": FunctionFragment;
    "setStaking(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addRecipient",
    values: [string, BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "adjustments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "authority", values?: undefined): string;
  encodeFunctionData(functionFragment: "bounty", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deriveRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distribute",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "epochLength",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "info", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "nextRewardAt",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "nextRewardFor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "nextRewardRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeRecipient",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "retrieveBounty",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthority",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDiscountRateStaking",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDiscountRateYield",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setStaking", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "addRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adjustments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "authority", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bounty", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deriveRate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "distribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "epochLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "info", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextRewardAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextRewardFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextRewardRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retrieveBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBounty", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDiscountRateStaking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDiscountRateYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setStaking", data: BytesLike): Result;

  events: {
    "AuthorityUpdated(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuthorityUpdated"): EventFragment;
}

export type AuthorityUpdatedEvent = TypedEvent<
  [string] & { authority: string }
>;

export class StakingDistributor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: StakingDistributorInterface;

  functions: {
    addRecipient(
      _recipient: string,
      _startRate: BigNumberish,
      _drs: BigNumberish,
      _dys: BigNumberish,
      _locked: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    adjustments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber] & {
        add: boolean;
        rate: BigNumber;
        target: BigNumber;
      }
    >;

    authority(overrides?: CallOverrides): Promise<[string]>;

    bounty(overrides?: CallOverrides): Promise<[BigNumber]>;

    deriveRate(
      _apy: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    distribute(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    epochLength(overrides?: CallOverrides): Promise<[number]>;

    info(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, string, boolean, number] & {
        start: BigNumber;
        drs: BigNumber;
        dys: BigNumber;
        recipient: string;
        locked: boolean;
        nextEpochTime: number;
      }
    >;

    nextRewardAt(
      _rate: BigNumberish,
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    nextRewardFor(
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    nextRewardRate(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    removeRecipient(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    retrieveBounty(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAuthority(
      _newAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBounty(
      _bounty: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDiscountRateStaking(
      _index: BigNumberish,
      _drs: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDiscountRateYield(
      _index: BigNumberish,
      _dys: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setStaking(
      _addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addRecipient(
    _recipient: string,
    _startRate: BigNumberish,
    _drs: BigNumberish,
    _dys: BigNumberish,
    _locked: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  adjustments(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [boolean, BigNumber, BigNumber] & {
      add: boolean;
      rate: BigNumber;
      target: BigNumber;
    }
  >;

  authority(overrides?: CallOverrides): Promise<string>;

  bounty(overrides?: CallOverrides): Promise<BigNumber>;

  deriveRate(_apy: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  distribute(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  epochLength(overrides?: CallOverrides): Promise<number>;

  info(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, string, boolean, number] & {
      start: BigNumber;
      drs: BigNumber;
      dys: BigNumber;
      recipient: string;
      locked: boolean;
      nextEpochTime: number;
    }
  >;

  nextRewardAt(
    _rate: BigNumberish,
    _recipient: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  nextRewardFor(
    _recipient: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  nextRewardRate(
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  removeRecipient(
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  retrieveBounty(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAuthority(
    _newAuthority: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBounty(
    _bounty: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDiscountRateStaking(
    _index: BigNumberish,
    _drs: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDiscountRateYield(
    _index: BigNumberish,
    _dys: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setStaking(
    _addr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addRecipient(
      _recipient: string,
      _startRate: BigNumberish,
      _drs: BigNumberish,
      _dys: BigNumberish,
      _locked: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    adjustments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber] & {
        add: boolean;
        rate: BigNumber;
        target: BigNumber;
      }
    >;

    authority(overrides?: CallOverrides): Promise<string>;

    bounty(overrides?: CallOverrides): Promise<BigNumber>;

    deriveRate(
      _apy: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    distribute(overrides?: CallOverrides): Promise<boolean>;

    epochLength(overrides?: CallOverrides): Promise<number>;

    info(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, string, boolean, number] & {
        start: BigNumber;
        drs: BigNumber;
        dys: BigNumber;
        recipient: string;
        locked: boolean;
        nextEpochTime: number;
      }
    >;

    nextRewardAt(
      _rate: BigNumberish,
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nextRewardFor(
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nextRewardRate(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeRecipient(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    retrieveBounty(overrides?: CallOverrides): Promise<BigNumber>;

    setAuthority(
      _newAuthority: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setBounty(_bounty: BigNumberish, overrides?: CallOverrides): Promise<void>;

    setDiscountRateStaking(
      _index: BigNumberish,
      _drs: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setDiscountRateYield(
      _index: BigNumberish,
      _dys: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setStaking(_addr: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "AuthorityUpdated(address)"(
      authority?: string | null
    ): TypedEventFilter<[string], { authority: string }>;

    AuthorityUpdated(
      authority?: string | null
    ): TypedEventFilter<[string], { authority: string }>;
  };

  estimateGas: {
    addRecipient(
      _recipient: string,
      _startRate: BigNumberish,
      _drs: BigNumberish,
      _dys: BigNumberish,
      _locked: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    adjustments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    authority(overrides?: CallOverrides): Promise<BigNumber>;

    bounty(overrides?: CallOverrides): Promise<BigNumber>;

    deriveRate(
      _apy: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    distribute(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    epochLength(overrides?: CallOverrides): Promise<BigNumber>;

    info(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    nextRewardAt(
      _rate: BigNumberish,
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nextRewardFor(
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nextRewardRate(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeRecipient(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    retrieveBounty(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAuthority(
      _newAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBounty(
      _bounty: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDiscountRateStaking(
      _index: BigNumberish,
      _drs: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDiscountRateYield(
      _index: BigNumberish,
      _dys: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setStaking(
      _addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addRecipient(
      _recipient: string,
      _startRate: BigNumberish,
      _drs: BigNumberish,
      _dys: BigNumberish,
      _locked: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    adjustments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    authority(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bounty(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deriveRate(
      _apy: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    distribute(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    epochLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    info(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nextRewardAt(
      _rate: BigNumberish,
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nextRewardFor(
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nextRewardRate(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeRecipient(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    retrieveBounty(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAuthority(
      _newAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBounty(
      _bounty: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDiscountRateStaking(
      _index: BigNumberish,
      _drs: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDiscountRateYield(
      _index: BigNumberish,
      _dys: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setStaking(
      _addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
