/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface StakingMockInterface extends ethers.utils.Interface {
  functions: {
    "THEO()": FunctionFragment;
    "basis()": FunctionFragment;
    "claimIndexCount()": FunctionFragment;
    "pushClaim(address,uint256)": FunctionFragment;
    "pushClaimForBond(address,uint256)": FunctionFragment;
    "sTHEO()": FunctionFragment;
    "stake(address,uint256,bool)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "THEO", values?: undefined): string;
  encodeFunctionData(functionFragment: "basis", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimIndexCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pushClaim",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pushClaimForBond",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "sTHEO", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [string, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "THEO", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "basis", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimIndexCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pushClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pushClaimForBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sTHEO", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;

  events: {};
}

export class StakingMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: StakingMockInterface;

  functions: {
    THEO(overrides?: CallOverrides): Promise<[string]>;

    basis(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimIndexCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    pushClaim(
      _to: string,
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pushClaimForBond(
      _to: string,
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sTHEO(overrides?: CallOverrides): Promise<[string]>;

    stake(
      _to: string,
      _amount: BigNumberish,
      _claim: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  THEO(overrides?: CallOverrides): Promise<string>;

  basis(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimIndexCount(overrides?: CallOverrides): Promise<BigNumber>;

  pushClaim(
    _to: string,
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pushClaimForBond(
    _to: string,
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sTHEO(overrides?: CallOverrides): Promise<string>;

  stake(
    _to: string,
    _amount: BigNumberish,
    _claim: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    THEO(overrides?: CallOverrides): Promise<string>;

    basis(overrides?: CallOverrides): Promise<string>;

    claimIndexCount(overrides?: CallOverrides): Promise<BigNumber>;

    pushClaim(
      _to: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    pushClaimForBond(
      _to: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sTHEO(overrides?: CallOverrides): Promise<string>;

    stake(
      _to: string,
      _amount: BigNumberish,
      _claim: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    THEO(overrides?: CallOverrides): Promise<BigNumber>;

    basis(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimIndexCount(overrides?: CallOverrides): Promise<BigNumber>;

    pushClaim(
      _to: string,
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pushClaimForBond(
      _to: string,
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sTHEO(overrides?: CallOverrides): Promise<BigNumber>;

    stake(
      _to: string,
      _amount: BigNumberish,
      _claim: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    THEO(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    basis(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimIndexCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pushClaim(
      _to: string,
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pushClaimForBond(
      _to: string,
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sTHEO(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    stake(
      _to: string,
      _amount: BigNumberish,
      _claim: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
